typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t ;

uint16_t FINGERPRINT_STARTCODE = 0xEF01;

//Packet identification

uint8_t FINGERPRINT_COMMANDPACKET = 0x01;

uint8_t FINGERPRINT_ACKPACKET = 0x07;
uint8_t FINGERPRINT_DATAPACKET = 0x02;
uint8_t FINGERPRINT_ENDDATAPACKET = 0x08;

//Instruction codes

uint8_t FINGERPRINT_VERIFYPASSWORD = 0x13;
uint8_t FINGERPRINT_SETPASSWORD = 0x12;
uint8_t FINGERPRINT_SETADDRESS = 0x15;
uint8_t FINGERPRINT_SETSYSTEMPARAMETER = 0x0E;
uint8_t FINGERPRINT_GETSYSTEMPARAMETERS = 0x0F;
uint8_t FINGERPRINT_TEMPLATEINDEX = 0x1F;
uint8_t FINGERPRINT_TEMPLATECOUNT = 0x1D;

uint8_t FINGERPRINT_READIMAGE = 0x01;

// Note: The documentation mean upload to host computer.
uint8_t FINGERPRINT_DOWNLOADIMAGE = 0x0A;

uint8_t FINGERPRINT_CONVERTIMAGE = 0x02;

uint8_t FINGERPRINT_CREATETEMPLATE = 0x05;
uint8_t FINGERPRINT_STORETEMPLATE = 0x06;
uint8_t FINGERPRINT_SEARCHTEMPLATE = 0x04;
uint8_t FINGERPRINT_LOADTEMPLATE = 0x07;
uint8_t FINGERPRINT_DELETETEMPLATE = 0x0C;

uint8_t FINGERPRINT_CLEARDATABASE = 0x0D;
uint8_t FINGERPRINT_GENERATERANDOMNUMBER = 0x14;
uint8_t FINGERPRINT_COMPARECHARACTERISTICS = 0x03;

//Note: The documentation mean download from host computer.
uint8_t FINGERPRINT_UPLOADCHARACTERISTICS = 0x09;
// Note: The documentation mean upload to host computer.
uint8_t FINGERPRINT_DOWNLOADCHARACTERISTICS = 0x08;

//Parameters of setSystemParameter()


int FINGERPRINT_SETSYSTEMPARAMETER_BAUDRATE = 4;
int FINGERPRINT_SETSYSTEMPARAMETER_SECURITY_LEVEL = 5;
int FINGERPRINT_SETSYSTEMPARAMETER_PACKAGE_SIZE = 6;

//Packet reply confirmations

uint8_t FINGERPRINT_OK = 0x00;
uint8_t FINGERPRINT_ERROR_COMMUNICATION = 0x01;

uint8_t FINGERPRINT_ERROR_WRONGPASSWORD = 0x13;

uint8_t FINGERPRINT_ERROR_INVALIDREGISTER = 0x1A;

uint8_t FINGERPRINT_ERROR_NOFINGER = 0x02;
uint8_t FINGERPRINT_ERROR_READIMAGE = 0x03;

uint8_t FINGERPRINT_ERROR_MESSYIMAGE = 0x06;
uint8_t FINGERPRINT_ERROR_FEWFEATUREPOINTS = 0x07;
uint8_t FINGERPRINT_ERROR_INVALIDIMAGE = 0x15;

uint8_t FINGERPRINT_ERROR_CHARACTERISTICSMISMATCH = 0x0A;

uint8_t FINGERPRINT_ERROR_INVALIDPOSITION = 0x0B;
uint8_t FINGERPRINT_ERROR_FLASH = 0x18;

uint8_t FINGERPRINT_ERROR_NOTEMPLATEFOUND = 0x09;

uint8_t FINGERPRINT_ERROR_LOADTEMPLATE = 0x0C;

uint8_t FINGERPRINT_ERROR_DELETETEMPLATE = 0x10;

uint8_t FINGERPRINT_ERROR_CLEARDATABASE = 0x11;

uint8_t FINGERPRINT_ERROR_NOTMATCHING = 0x08;

uint8_t FINGERPRINT_ERROR_DOWNLOADIMAGE = 0x0F;
uint8_t FINGERPRINT_ERROR_DOWNLOADCHARACTERISTICS = 0x0D;

//Unknown error codes

uint8_t FINGERPRINT_ADDRCODE = 0x20;
uint8_t FINGERPRINT_PASSVERIFY = 0x21;

uint8_t FINGERPRINT_PACKETRESPONSEFAIL = 0x0E;

uint8_t FINGERPRINT_ERROR_TIMEOUT = 0xFF;
uint8_t FINGERPRINT_ERROR_BADPACKET = 0xFE;

//Char buffers


uint8_t FINGERPRINT_CHARBUFFER1 = 0x01;
//Char buffer 1


uint8_t FINGERPRINT_CHARBUFFER2 = 0x02;
//Char buffer 2

